#!/bin/sh
#
# Sets a system up for a candlepin development environment (minus a db,
# handled separately), and an initial clone of candlepin.

export JAVA_HOME=/usr/lib/jvm/java-1.7.0/

yum -y install rsyslog wget vim-enhanced python-pip git ruby rubygems ruby-devel gcc tomcat java-1.7.0-openjdk-devel liquibase libxml2-python openssl gettext

# Setup for autoconf:
mkdir /etc/candlepin
echo "# AUTOGENERATED" > /etc/candlepin/candlepin.conf

# Create an initial candlepin checkout at /candlepin in image to help decrease
# the amount of time to run tests later on.
git clone https://github.com/candlepin/candlepin.git /candlepin
cd /candlepin/server

# Install all ruby deps:
gem install bundler
bundle install

# Installs all Java deps into the image, big time saver:
buildr clean test=no package
