#!/bin/bash

function shutdown()
{
    /usr/libexec/tomcat/server stop
}

date
echo "Starting Tomcat"
export CATALINA_PID=/tmp/$$
export JAVA_HOME="/usr/lib/jvm/jre"

. /usr/libexec/tomcat/server start

# Allow any signal which would kill a process to stop Tomcat
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

echo "Waiting for `cat $CATALINA_PID`"
wait `cat $CATALINA_PID`
