source 'https://rubygems.org'

gem 'buildr', '1.4.19'
# Not a typo - we use both buildr and buildr
gem 'builder'
gem 'rspec'
gem 'rest-client', '~> 1.6.0'
gem 'mime-types', '~> 1.25.0'
gem 'oauth'
gem 'parallel_tests'
gem 'buildr-findBugs'
gem 'pmd'
gem 'stringex'
gem 'pry'
gem 'digest-murmurhash'
