source 'https://rubygems.org'

gem 'buildr', '1.4.19'
gem 'rspec'
gem 'rest-client', '~> 1.6.0'
gem 'mime-types', '~> 1.25.0'
gem 'oauth'
gem 'parallel_tests'
gem 'buildr-findBugs'
gem 'pmd'
gem 'pry'
