# the ampersand and name create an alias to an item
# the "<<" is used to merge two hashes together and the asterisk plus a name dereferences an alias
# See http://viewsourcecode.org/why/redhanded/bits/yamlSMergeKey.html

common:
  static: &common_static
    logdriver_class: "net.rkbloom.logdriver.LogDriver"
  server: &common_server
    <<: *common_static
    username: "candlepin"
    password: ""
  gutterball: &common_gutterball
    <<: *common_static
    username: "gutterball"
    password: ""

postgresql: &default
  static: &postgresql_static
    driver_class: "org.postgresql.Driver"
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
    quartz_driver: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
  server:
    <<: *common_server
    <<: *postgresql_static
    jdbc_url: "jdbc:postgresql:$DB_NAME"
  gutterball:
    <<: *common_gutterball
    <<: *postgresql_static
    jdbc_url: "jdbc:postgresql:$DB_NAME"

# Buildr's default environment is "development" so
# by default, go against postgresql.
development:
  <<: *default

oracle:
  static: &oracle_static
    driver_class: "oracle.jdbc.OracleDriver"
    dialect: "org.hibernate.dialect.Oracle10gDialect"
    quartz_driver: "org.quartz.impl.jdbcjobstore.oracle.OracleDelegate"
  server:
    <<: *common_server
    <<: *oracle_static
    jdbc_url: "jdbc:oracle:thin:@//localhost:1521/XE"
    password: "candlepin"
  gutterball:
    <<: *common_gutterball
    <<: *oracle_static
    jdbc_url: "jdbc:oracle:thin:@//localhost:1521/XE"
    password: "gutterball"

mysql:
  static: &mysql_static
    driver_class: "com.mysql.jdbc.Driver"
    dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
    quartz_driver: "org.quartz.impl.jdbcjobstore.StdJDBCDelegate"
  server:
    <<: *common_server
    <<: *mysql_static
    jdbc_url: "jdbc:mysql:///$DB_NAME"
  gutterball:
    <<: *common_server
    <<: *mysql_static
    jdbc_url: "jdbc:mysql:///$DB_NAME"
