name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/*
runs:
  using: "composite"
  steps:
    - env:
        VAR_FILE_PATH: ${{ inputs.varFilePath }}
      run: |
        sed "" "$VAR_FILE_PATH" >> "$GITHUB_ENV"
      shell: bash
