/**
 * Copyright (c) 2009 Red Hat, Inc.
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */
package org.fedoraproject.candlepin.auth;

import java.util.Arrays;
import org.fedoraproject.candlepin.model.Consumer;
import org.fedoraproject.candlepin.model.Entitlement;
import org.fedoraproject.candlepin.model.EntitlementCertificate;
import org.fedoraproject.candlepin.model.Owner;
import org.fedoraproject.candlepin.model.Permission;
import org.fedoraproject.candlepin.model.Pool;

/**
 *
 */
public class ConsumerPrincipal extends Principal {

    private Consumer consumer;

    public ConsumerPrincipal(Consumer consumer) {
        super(Arrays.asList(new Permission[] {new Permission(consumer.getOwner(), 
            Access.CONSUMER)}));

        this.consumer = consumer;
    }
    
    public Consumer consumer() {
        return consumer;
    }

    // Note: automatically generated by Netbeans
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ConsumerPrincipal other = (ConsumerPrincipal) obj;
        if (this.consumer != other.consumer &&
                (this.consumer == null || !this.consumer.equals(other.consumer))) {
            return false;
        }
        return true;
    }

    // Note: automatically generated by Netbeans
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + (this.consumer != null ? this.consumer.hashCode() : 0);
        return hash;
    }

    @Override
    public String getPrincipalName() {       
        return consumer.getName();
    }     

    public String getType() {
        return Principal.CONSUMER_TYPE;
    }

    // Access controls
    @Override
    public boolean canAccess(Owner owner) {
        return false;
    }

    @Override
    public boolean canAccess(Consumer consumer) {
        return this.consumer.getUuid().equals(consumer.getUuid());
    }

    @Override
    public boolean canAccess(Entitlement entitlement) {
        return canAccess(entitlement.getConsumer());
    }

    @Override
    public boolean canAccess(EntitlementCertificate entitlementCert) {
        return canAccess(entitlementCert.getEntitlement());
    }

    @Override
    public boolean canAccess(Pool pool) {
        return this.consumer.getOwner().getKey().equals(pool.getOwner().getKey());
    }
}
