---
- name: "Disable SELinux"
  become: true
  tags:
    - system
    - candlepin
  block:
    - name: "Check current SELinux mode"
      ansible.builtin.command:
        cmd: getenforce
      register: cp_selinux_status
      changed_when: false

    - name: "Disable SELinux for the current boot"
      ansible.builtin.command:
        cmd: setenforce 0
      when: cp_selinux_status.stdout == "Enforcing"

    - name: "Disable SELinux permanently"
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: SELINUX=disabled

- name: "Update system packages" # noqa: command-instead-of-module
  become: true
  ansible.builtin.command:
    argv:
      - dnf
      - update
      - -y
      - --allowerasing
  environment:
    LC_ALL: C
  register: cp_system_package_update
  changed_when: "'Nothing to do.' not in cp_system_package_update.stdout"
  tags:
    - system
    - system_update
    - candlepin

- name: "Install Candlepin requirements" # noqa: command-instead-of-module
  become: true
  ansible.builtin.command:
    argv:
      - dnf
      - install
      - -y
      - git
      - gcc
      - make
      - java-17-openjdk-devel
      - gettext
      - openssl
      - platform-python
      - python36
      - python3-libxml2
      - python3-requests
      - tomcat
      - unzip
      - wget
      - zlib
      - zlib-devel
      - createrepo_c
      - rpm-build
      - rpm-sign
  environment:
    LC_ALL: C
  register: cp_candlepin_requirements_install
  changed_when: "'Nothing to do.' not in cp_candlepin_requirements_install.stdout"
  tags:
    - base_deps
    - candlepin

# Impl note:
# The invocations of alternatives need to be run in the context of the original user, but with
# root permissions. Using become and the raw shell command invokes these in root's environment,
# which will fail at best, or silently map the wrong command at worst.
- name: "Configure alternatives: python"
  ansible.builtin.shell: sh -c 'sudo alternatives --set python /usr/bin/python3'
  changed_when: false
  tags:
    - base_deps
    - candlepin

- name: "Configure alternatives: java"
  ansible.builtin.shell: sh -c 'sudo alternatives --set java /usr/lib/jvm/java-17-openjdk-*/bin/java'
  changed_when: false
  tags:
    - base_deps
    - candlepin

- name: "Configure alternatives: javac"
  ansible.builtin.shell: sh -c 'sudo alternatives --set javac /usr/lib/jvm/java-17-openjdk-*/bin/javac'
  changed_when: false
  tags:
    - base_deps
    - candlepin

- name: "Update Tomcat configuration to use Alternatives-configured Java"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/tomcat/tomcat.conf
    regexp: "JAVA_HOME="
    line: "JAVA_HOME=\"/usr/lib/jvm/java\""
  tags:
    - base_deps
    - candlepin

- name: "Check permanent ports in firewalld" # noqa: command-instead-of-module
  become: true
  ansible.builtin.command:
    argv:
      - firewall-cmd
      - --permanent
      - "--query-port={{ item }}/tcp"
  register: cp_firewalld_port_status
  changed_when: false
  failed_when: cp_firewalld_port_status.rc not in [0, 1]
  loop:
    - 22
    - 443
    - 8080
    - 8443
  when:
    - "'services' in ansible_facts"
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service'].state == 'running'"
  tags:
    - system
    - candlepin

- name: "Enable permanent ports in firewalld" # noqa: command-instead-of-module
  become: true
  ansible.builtin.command:
    argv:
      - firewall-cmd
      - --permanent
      - "--add-port={{ item.item }}/tcp"
  changed_when: true
  loop: "{{ cp_firewalld_port_status.results | default([]) }}"
  loop_control:
    label: "{{ item.item }}/tcp"
  when:
    - "'services' in ansible_facts"
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service'].state == 'running'"
    - item.rc == 1
  tags:
    - system
    - candlepin

- name: "Check permanent ports offline" # noqa: command-instead-of-module
  become: true
  ansible.builtin.command:
    argv:
      - firewall-offline-cmd
      - "--query-port={{ item }}/tcp"
  register: cp_firewalld_offline_port_status
  changed_when: false
  failed_when: cp_firewalld_offline_port_status.rc not in [0, 1]
  loop:
    - 22
    - 443
    - 8080
    - 8443
  when:
    - "'services' in ansible_facts"
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service'].state != 'running'"
  tags:
    - system
    - candlepin

- name: "Enable permanent ports offline" # noqa: command-instead-of-module
  become: true
  ansible.builtin.command:
    argv:
      - firewall-offline-cmd
      - "--add-port={{ item.item }}/tcp"
  changed_when: true
  loop: "{{ cp_firewalld_offline_port_status.results | default([]) }}"
  loop_control:
    label: "{{ item.item }}/tcp"
  when:
    - "'services' in ansible_facts"
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service'].state != 'running'"
    - item.rc == 1
  tags:
    - system
    - candlepin
