version: '3'
services:
  db:
    image: ${REGISTRY}/mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  candlepin:
    image: ${REGISTRY}/candlepin-base-cs8
    environment:
      USING_MYSQL: "true"
      DBHOSTNAME: db
    ports:
      - "8443:8443"
      - "8080:8080"
      - "22:22"
    privileged: true
    volumes:
      - ../:/candlepin-dev
    depends_on:
      - db
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
