/**
 * Copyright (c) 2009 - 2017 Red Hat, Inc.
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */
package org.candlepin.dto;

import org.candlepin.model.CandlepinQuery;

/**
 * The ModelTranslator interface defines common functionality required by every ModelTranslator
 * implementation.
 */
public interface ModelTranslator {

    // TODO: Maybe move the input/output class stuff to ObjectTranslator.getInputClass/getOutputClass
    // and drop it from the registration bits here?

    /**
     * Registers the given translator as a translator for the given input to output class mapping.
     * This method returns any translator has been previously translated for the given mapping.
     *
     * @param translator
     *  The translator to register for the given class
     *
     * @param inputClass
     *  The input type handled by the specified translator
     *
     * @param outputClass
     *  The output type of the objects generated by the given translator
     *
     * @throws IllegalArgumentException
     *  if translator is null, inputClass is null or outputClass is null
     *
     * @return
     *  The translator previously registered for the given classes, or null if the classes did not
     *  have a previously registered translator
     */
    <I, O> ObjectTranslator<I, O> registerTranslator(ObjectTranslator<I, O> translator, Class<I> inputClass,
        Class<O> outputClass);

    /**
     * Unregisters and returns any translator associated with the given class. If the class has not
     * been associated with a translator, this method returns null.
     *
     * @param inputClass
     *  The input type for the translator to unregister
     *
     * @param outputClass
     *  The output type for the translator to unregister
     *
     * @return
     *  The previously registered translator for the given class, or null a translator had not been
     *  registered
     */
    <I, O> ObjectTranslator<I, O> unregisterTranslator(Class<I> inputClass, Class<O> outputClass);

    /**
     * Unregisters the specified translator from any class mappings to which it's registered.
     *
     * @param translator
     *  The translator to unregister
     *
     * @throws IllegalArgumentException
     *  if translator is null
     *
     * @return
     *  The number of mappings from which the translator was unregistered
     */
    int unregisterTranslator(ObjectTranslator translator);

    /**
     * Retrieves the translator registered for the specified class. If a translator has not been
     * registered for the given class, this method returns null.
     * <p></p>
     * Note that unlike the findTranslator methods, this method will only perform an exact class
     * match, and will not attempt to find a suitable translator if the given class does not have
     * an explicitly registered translator.
     *
     * @param inputClass
     *  The model class for which to retrieve a translator
     *
     * @throw IllegalArgumentException
     *  if inputClass is null
     *
     * @return
     *  The translator registered for the given class, or null if a translator has not yet been
     *  registered
     */
    <I, O> ObjectTranslator<I, O> getTranslator(Class<I> inputClass, Class<O> outputClass);

    /**
     * Finds a translator for the given class mappings. If a translator cannot be found, this method
     * returns throws an exception.
     *
     * @param inputClass
     *  The input type for which to find a translator
     *
     * @param outputClass
     *  The output type for which to find a translator
     *
     * @throws IllegalArgumentException
     *  if inputClass is null
     *
     * #throws TranslationException
     *  if an appropriate translator could not be found
     *
     * @return
     *  a translator for the given source object
     */
    <I, O> ObjectTranslator<I, O> findTranslatorByClass(Class<I> inputClass, Class<O> outputClass);

    /**
     * Finds a translator for a specific input object instance. If an appropriate translator cannot
     * be found, this method throws an exception.
     *
     * @param instance
     *  The input object for which to find a translator
     *
     * @param outputClass
     *  The output type for which to find a translator
     *
     * @throws IllegalArgumentException
     *  if instance is null
     *
     * #throws TranslationException
     *  if an appropriate translator could not be found
     *
     * @return
     *  a translator for the given object instance
     */
    <I, O> ObjectTranslator<I, O> findTranslatorByInstance(I instance, Class<O> outputClass);

    /**
     * Builds a new instance from the given input object using the translators registered to
     * translator to process the object and any nested objects it contains. If this factory does
     * not have a registered translator which can process the input object and its nested objects,
     * this method throws a TransformationException. If the input object is null, this method
     * returns null.
     *
     * @param input
     *  The input object for which to build a DTO
     *
     * #throws TranslationException
     *  if a translator cannot be found for the input object or any of its nested objects
     *
     * @return
     *  a newly translated instance of the input object, or null if the input object is null
     */
    <I, O> O translate(I input, Class<O> outputClass);

    /**
     * Applies a translate to the specified query that uses this ModelTranslator to translate the
     * entities fetched by the query to DTOs. If this factory does not have a registered translator
     * which can process the query's entities and their nested objects, this method will complete
     * as normal, but the CandlepinQuery will throw a DTOException when it fetches any results.
     *
     * @param query
     *  The CandlepinQuery to translate
     *
     * @throws IllegalArgumentException
     *  if query is null
     *
     * #throws TranslationException
     *  if a translator cannot be found for the source object or any of its nested objects
     *
     * @return
     *  A translated CandlepinQuery using this ModelTranslator for its element transformation
     */
    <I, O> CandlepinQuery<O> translateQuery(CandlepinQuery<I> query, Class<O> outputClass);

    // /**
    //  * Populates the given destination object with data from the source object, using the specified
    //  * ModelTranslator to populate nested objects and object collections. If a ModelTranslator is
    //  * not provided, any nested objects or object collections will be set to null or empty values as
    //  * appropriate.
    //  *
    //  * @param source
    //  *  The source object from which to fetch data
    //  *
    //  * @param destination
    //  *  The destination object to populate
    //  *
    //  * @throws IllegalArgumentException
    //  *  if either source or destination objects are null
    //  *
    //  * @throws TranslationException
    //  *  if a translator cannot be found for the source object or any of its nested objects
    //  *
    //  * @return
    //  *  The populated destination object
    //  */
    // O populate(I source, O destination);

}
