# ENV Variables
CANDLEPIN_HOME=`dirname $0`
M2_REPO=$HOME/.m2/repository
cp_entries=( $CANDLEPIN_HOME/target/candlepin-client-0.4.jar $M2_REPO/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar $M2_REPO/commons-codec/commons-codec/1.4/commons-codec-1.4.jar $M2_REPO/commons-cli/commons-cli/1.2/commons-cli-1.2.jar $M2_REPO/commons-pool/commons-pool/1.2/commons-pool-1.2.jar $M2_REPO/commons-collections/commons-collections/3.1/commons-collections-3.1.jar $M2_REPO/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar $M2_REPO/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar $M2_REPO/commons-lang/commons-lang/2.5/commons-lang-2.5.jar $M2_REPO/org/jboss/resteasy/jaxrs-api/1.2.1.GA/jaxrs-api-1.2.1.GA.jar $M2_REPO/org/jboss/resteasy/resteasy-jaxrs/1.2.1.GA/resteasy-jaxrs-1.2.1.GA.jar $M2_REPO/org/jboss/resteasy/resteasy-jaxb-provider/1.2.1.GA/resteasy-jaxb-provider-1.2.1.GA.jar $M2_REPO/org/jboss/resteasy/resteasy-jackson-provider/1.2.1.GA/resteasy-jackson-provider-1.2.1.GA.jar $M2_REPO/org/jboss/resteasy/resteasy-guice/1.2.1.GA/resteasy-guice-1.2.1.GA.jar $M2_REPO/javax/persistence/persistence-api/1.0/persistence-api-1.0.jar $M2_REPO/xalan/xalan/2.6.0/xalan-2.6.0.jar $M2_REPO/org/scannotation/scannotation/1.0.2/scannotation-1.0.2.jar $M2_REPO/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar $M2_REPO/org/slf4j/slf4j-api/1.5.8/slf4j-api-1.5.8.jar $M2_REPO/org/slf4j/slf4j-log4j12/1.5.8/slf4j-log4j12-1.5.8.jar $M2_REPO/org/freemarker/freemarker/2.3.15/freemarker-2.3.15.jar $M2_REPO/junit/junit/4.5/junit-4.5.jar $M2_REPO/org/mockito/mockito-all/1.8.1/mockito-all-1.8.1.jar $M2_REPO/log4j/log4j/1.2.14/log4j-1.2.14.jar $M2_REPO/org/bouncycastle/bcprov-jdk16/1.44/bcprov-jdk16-1.44.jar $M2_REPO/org/bouncycastle/bcpg-jdk16/1.44/bcpg-jdk16-1.44.jar $M2_REPO/jdom/jdom/1.0/jdom-1.0.jar $M2_REPO/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar $M2_REPO/org/xnap/commons/gettext-commons/0.9.6/gettext-commons-0.9.6.jar $M2_REPO/org/codehaus/jackson/jackson-core-lgpl/1.4.1/jackson-core-lgpl-1.4.1.jar $M2_REPO/org/codehaus/jackson/jackson-mapper-lgpl/1.4.1/jackson-mapper-lgpl-1.4.1.jar $M2_REPO/org/codehaus/jackson/jackson-jaxrs/1.4.1/jackson-jaxrs-1.4.1.jar  )

for entry in ${cp_entries[@]}
do
    CLASSPATH=$CLASSPATH:$entry
done
#echo $CLASSPATH
java -classpath $CLASSPATH org.fedoraproject.candlepin.client.CLIMain $*
