#!/bin/sh
#
# Sets a system up for a candlepin development environment (minus a db,
# handled separately), and an initial clone of candlepin.

set -e

export JAVA_HOME=/usr/lib/jvm/java-1.7.0/
export HOME=/root

PACKAGES=(
    rsyslog
    wget
    vim-enhanced
    python-pip
    git
    tig
    rubygems
    ruby-devel
    gcc
    tomcat
    java-1.7.0-openjdk-devel
    liquibase
    libxml2-python
    openssl
    gettext
    tmux
)

yum -y install ${PACKAGES[@]}

# Setup for autoconf:
mkdir /etc/candlepin
echo "# AUTOGENERATED" > /etc/candlepin/candlepin.conf

cat > /root/.bashrc <<BASHRC
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
BASHRC

# Create an initial candlepin checkout at /candlepin in image to help decrease
# the amount of time to run tests later on.
git clone https://github.com/candlepin/candlepin.git /candlepin
cd /candlepin

# Allow for grabbing specific pull requests
git config --add remote.origin.fetch "+refs/pull/*:refs/remotes/origin/pr/*"

# Install all ruby deps:
gem install bundler
bundle install

# Installs all Java deps into the image, big time saver:
buildr artifacts
