library identifier: 'fh-pipeline-library@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/candlepin/fh-pipeline-library.git',
   credentialsId: 'github-api-token-as-username-password'])

pipeline {
    agent { label 'candlepin' }
    options {
        skipDefaultCheckout true
        timeout(time: 16, unit: 'HOURS')
    }
    environment {
        CANDLEPIN_QUAY_BOT = credentials("candlepin-quay-bot")
    }
    stages {
        stage('Trust') {
            steps {
                enforceTrustedApproval("candlepin","rhsm-jenkins-github-app")
            }
        }
        stage('Test') {
            parallel {
                stage('unit') {
                    // ensures that this stage will get assigned its own workspace
                    agent { label 'candlepin' }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/unit-tests.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('Upload-PR-to-SonarQube') {
                    agent { label 'candlepin' }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/upload-on-sonarqube.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('Upload-Branch-to-SonarQube') {
                    agent { label 'candlepin' }
                    environment {
                        BRANCH_UPLOAD = 'true'
                    }
                    when {
                        not {
                            changeRequest()
                        }
                    }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/upload-on-sonarqube.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('checkstyle') {
                    agent { label 'candlepin' }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/lint.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('rspec-postgresql') {
                    agent { label 'candlepin' }
                    environment {
                        CANDLEPIN_DATABASE = 'postgresql'
                        CP_TEST_ARGS = '-r'
                    }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/rspec-tests.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('rspec-mysql') {
                    agent { label 'candlepin' }
                    environment {
                        CANDLEPIN_DATABASE = 'mysql'
                        CP_TEST_ARGS = '-r'
                    }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/rspec-tests.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('rspec-postgres-hosted') {
                    agent { label 'candlepin' }
                    environment {
                        CANDLEPIN_DATABASE = 'postgresql'
                        CP_TEST_ARGS = '-H -k'
                    }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/rspec-tests.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('rspec-mysql-hosted') {
                    agent { label 'candlepin' }
                    environment {
                        CANDLEPIN_DATABASE = 'mysql'
                        CP_TEST_ARGS = '-H -k'
                    }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/rspec-tests.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
                stage('bugzilla-reference') {
                    environment {
                        GITHUB_TOKEN = credentials('github-api-token-as-username-password')
                    }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'python jenkins/check_pr_branch.py $CHANGE_ID'
                    }
                }
                stage('validate-translation') {
                    agent { label 'candlepin' }
                    steps {
                        sh 'sudo chown -R jenkins:jenkins $WORKSPACE'
                        checkout scm
                        sh 'docker login -u "$CANDLEPIN_QUAY_BOT_USR" -p "$CANDLEPIN_QUAY_BOT_PSW" quay.io'
                        sh 'sh jenkins/candlepin-validate-text.sh'
                    }
                    post {
                        always {
                            sh 'sh jenkins/cleanup.sh'
                        }
                    }
                }
            }
        }
    }
}
