/*
 * Copyright (c) 2009 - 2026 Red Hat, Inc.
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */
package org.candlepin.pki;

import java.security.KeyException;
import java.security.KeyPair;



/**
 * The KeyPairGenerator provides a common interface for generating KeyPair instances, consisting of a public
 * and private key. Each key pair generated by a key pair generator will not be associated with any consumer,
 * organization, or any other such logical Candlepin entity. Receivers of the key pairs are expected to
 * assigned or establish relationships upon generation.
 */
public interface KeyPairGenerator {

    /**
     * Fetches the scheme backing this key pair generator. Cryptographic operations performed by this
     * generator will use the algorithms and keys defined by this scheme.
     *
     * @return
     *  the cryptographic scheme used by this key pair generator
     */
    Scheme getCryptoScheme();

    /**
     * Generates a new, unassociated key pair consisting of a public and private key.
     *
     * @throws KeyException
     *  if an exception occurs during generation of the key pair
     *
     * @return
     *  a KeyPair instance containing a new public and private key
     */
    KeyPair generateKeyPair() throws KeyException;
}
