/**
 * Copyright (c) 2009 Red Hat, Inc.
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */
package org.fedoraproject.candlepin.policy;

import java.util.List;

/**
 * Results of an enforcer validation. Basically used to support multiple 
 * errors being generated by an attempt to consume (perhaps multiple attribute 
 * checks failed), but also the possibility of warnings, which do not actually
 * prevent the entitlement from being given out.
 * 
 */
public class ValidationResult {
	
	private List<ValidationError> errors;
	private List<ValidationWarning> warnings;
	
	public List<ValidationError> getErrors() {
		return errors;
	}
	
	public void setErrors(List<ValidationError> errors) {
		this.errors = errors;
	}
	
	public List<ValidationWarning> getWarnings() {
		return warnings;
	}
	
	public void setWarnings(List<ValidationWarning> warnings) {
		this.warnings = warnings;
	}
}
