#!/bin/sh 
function evalrc ()
{
    if [ "$1" -ne "0" ] ; then
        echo "$2"
        exit
    fi
}

function gendb ()
{
	echo "============ generating a new db =============="
    buildr candlepin:genschema
    evalrc $? "schema generation failed"

    dropdb -U candlepin candlepin
    evalrc $? "dropdb failed"

    createdb -U candlepin candlepin
    evalrc $? "createdb failed"

    psql -U candlepin candlepin < target/schemagen/candlepin-proxy.sql
    evalrc $? "schema creation failed"

    psql -U candlepin < code/schema/quartz/tables_postgres.sql
    evalrc $? "quartz schema failed"
}

function deploy ()
{
    VERSION="`grep Version: candlepin.spec | cut --delim=' ' -f2`"
    if [ -z $CLEAN ] ; then
        $SUDO rm -rf $DEPLOY
    else
        $SUDO rm -rf $CLEAN
    fi
    $SUDO cp target/candlepin-$VERSION.war $DEPLOY
}

function stopappserver ()
{
    # tc rpm /sbin/service tomcat6 stop
    # tc opt $TC_HOME/bin/catalina.sh stop
    # jboss opt $JBOSS_HOME/bin/shutdown.sh
    $STOP
}

function isrpm ()
{
    echo $1 | grep "var/lib" > /dev/null
    return $?
}


function update_keystore
{
	if [ "$FORCECERT" = "" ]; then
	    echo "Using existing keystore"
	else
	    echo "Move the keystore to tomcats location"
	    cp /etc/candlepin/certs/keystore $CONTAINER_CONF_DIR/keystore
	fi
}

function upload_products
{
    if [ -z "$IMPORTDIR" ]; then
	echo
	echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	echo
	echo "Please point IMPORTDIR to the location of the product data "
	echo
	echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	return
    fi
#    $IMPORTDIR/import_product_certs.py $CERTDIR/*.pem > $CERTDIR/deploy.sql
    if [ "$IMPORTDIR" != "" ]; then
	`dirname $0`/import_products.rb  $IMPORTDIR/import_products.json
    fi
}

function create_var_lib_candlepin
{
    sudo mkdir -p /var/lib/candlepin
    sudo chown tomcat:tomcat /var/lib/candlepin
}

function create_var_log_candlepin
{
    sudo mkdir -p /var/log/candlepin
    sudo chown tomcat:tomcat /var/log/candlepin
}

function create_var_cache_candlepin
{
    sudo mkdir -p /var/cache/candlepin
    sudo chown tomcat:tomcat /var/cache/candlepin
}

# Read in user defined variables
if [ -f $HOME/.candlepinrc ] ; then
    source $HOME/.candlepinrc
fi

if [ "$JBOSS_HOME" != "" ]; then
    # we're using JBOSS AS
    isrpm $JBOSS_HOME

    if [ "$?" -ne 0 ]; then
        START="$JBOSS_HOME/bin/run.sh 2>&1 > console.log &"
        STOP="$JBOSS_HOME/bin/shutdown.sh --shutdown"
        DEPLOY="$JBOSS_HOME/server/default/deploy/"
    else
        SUDO="sudo"
        START="sudo /sbin/service jbossas start"
        STOP="sudo /sbin/service jbossas stop"
        DEPLOY="$JBOSS_HOME/server/default/deploy/"
    fi
    CONTAINER_CONF_DIR="$JBOSS_HOME/conf"
    CLEAN="$JBOSS_HOME/server/default/deploy/candlepin*"
else
    # use tomcat 6, if not specified
    TC=tomcat6
    if [ -z $TC_HOME ]; then
        TC_HOME=/var/lib/$TC
    fi

    isrpm $TC_HOME

    if [ "$?" -ne 0 ]; then
        START="$TC_HOME/bin/catalina.sh start"
        STOP="$TC_HOME/bin/catalina.sh stop"
        CONTAINER_CONF_DIR="$TC_HOME/conf"
    else
        SUDO="sudo"
        START="sudo /sbin/service $TC start"
        STOP="sudo /sbin/service $TC stop"
        CONTAINER_CONF_DIR="/etc/$TC"
    fi

    DEPLOY="$TC_HOME/webapps/candlepin.war"
    CLEAN="$TC_HOME/webapps/candlepin/"
fi

# stop the appserver
eval $STOP

# generate the postgresql DB

buildr clean package test=no

if [ "$GENDB" != "" ]; then
	gendb	
fi

# generate SSL certs if they are needed
sh -x `dirname $0`/gen-certs

# update keystore file and put it into tomcat's conf directory
update_keystore

# update server.xml
sudo python buildconf/scripts/update-server-xml.py $CONTAINER_CONF_DIR

create_var_lib_candlepin
create_var_log_candlepin
create_var_cache_candlepin

# deploy the webapp
deploy

eval $START

sleep 10
echo "Initializing Candlepin..."
wget -qO- http://localhost:8080/candlepin/admin/init

upload_products
