#!/bin/bash

CERTS_HOME=/etc/candlepin/certs
CA_KEY=$CERTS_HOME/candlepin-ca.key
CA_CERT=$CERTS_HOME/candlepin-ca.crt


rpm -q openssl > /dev/null
if [ "$?" -ne 0 ]; then
    echo "Certificate generation failed - please install openssl."
    exit 1
fi

if [ ! -d $CERTS_HOME ]; then
    echo "Creating $CERTS_HOME"
    sudo mkdir -p $CERTS_HOME
fi

HOSTNAME=$(hostname)

if [ -f $CA_KEY ] && [ -f $CA_CERT ]; then
    echo "Certificates are already present."
else
    echo "Creating CA private key"
    sudo openssl genrsa -out $CA_KEY 1024
    echo "Creating CA certificate"
    sudo openssl req -new -x509 -days 365 -key $CA_KEY -out $CA_CERT -subj "/CN=$HOSTNAME/C=US/L=Raleigh/"
fi
