---
roles:
  - src: https://github.com/candlepin/ansible-role-candlepin.git
    name: candlepin
    version: master

  - src: git+https://github.com/Januson/rvm1-ansible.git
    version: skip-rubies

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.mysql
  - name: community.postgresql
