/**
 * Copyright (c) 2009 - 2019 Red Hat, Inc.
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */
package org.candlepin.policy;

import org.xnap.commons.i18n.I18n;


/**
 * Represents a validation warning generated by rules processing.
 */
public interface RulesValidationWarning {

    /**
     * Builds a translated warning message for the validation warning that this object represents.
     * @param i18n object that provides internationalization
     * @param args positional object arguments for the warning message
     * @return the final translated warning message in text
     */
    String buildWarningMessage(I18n i18n, Object... args);
}
