name: AutoAssignReviewer

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Run assignment of reviewer team
        uses: nikosmoum/auto-assign-reviewer-team@v0.5
        with:
          githubToken: ${{ secrets.AutoAssignReviewerSecret }}
          teamName: 'candlepin-server'
