name: AutoAssignReviewer

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign-reviewer:
    runs-on: ubuntu-latest
    steps:
#      - name: Run assignment of reviewer team
#        uses: nikosmoum/auto-assign-reviewer-team@v0.5
#        with:
#          githubToken: ${{ secrets.GITHUB_TOKEN }}
#          teamName: 'candlepin-server'
#      - name: Run assignment of reviewer team
#        run: |
#         curl -L \
#           -X POST \
#           -H "Accept: application/vnd.github+json" \
#           -H "Authorization: Bearer <YOUR-TOKEN>"\
#           -H "X-GitHub-Api-Version: 2022-11-28" \
#           https://api.github.com/repos/OWNER/REPO/pulls/PULL_NUMBER/requested_reviewers \
#           -d '{"team_reviewers":["justice-league"]}'
      - name: Run assignment of reviewer team
        uses: octokit/request-action@v2.x
        id: add_pr_comment
        with:
          route: POST /repos/:repository/pulls/:pr_number/requested_reviewers
          repository: ${{ github.repository }}
          pr_number: ${{ github.event.number }}
          body: |
            team_reviewers: candlepin-server
        env:
          GITHUB_TOKEN: ${{ secrets.AutoAssignReviewerSecret }}